// actions.js

export const SIGN_UP = 'SIGN_UP';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_BUDDY = 'UPDATE_BUDDY';
export const TOGGLE_AVAILABILITY = 'TOGGLE_AVAILABILITY';
export const UPDATE_USERS_CONVERSATION_FIELD = 'UPDATE_USERS_CONVERSATION_FIELD';
export const DELETE_USER_UNSUBSCRIBE = 'DELETE_USER_UNSUBSCRIBE';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const UPDATE_CONVERSATION_TITLE = 'UPDATE_CONVERSATION_TITLE';
export const UPDATE_CONVERSATION_TEXT = 'UPDATE_CONVERSATION_TEXT';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPDATE_LISTENER = 'UPDATE_LISTENER';
export const TOGGLE_IS_CLOSED = 'TOGGLE_IS_CLOSED';
export const TOGGLE_IS_PRIVATE = 'TOGGLE_IS_PRIVATE';
export const CLOSE_CONVERSATION = 'CLOSE_CONVERSATION';
